version: "3.9"

services:
  # MariaDB Container --------------------------------------------------------
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - database:/var/lib/mysql/
    networks:
      - inception
    init: true
    restart: on-failure
    env_file:
      - .env

  # WordPress Container ------------------------------------------------------
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - inception
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - mariadb

  # Nginx Container ----------------------------------------------------------
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx/
      args:
        SSL_CERTIFICATE_FOLDER: ${SSL_CERTIFICATE_FOLDER}
        SSL_CERTIFICATE_PATH: ${SSL_CERTIFICATE_PATH}
        SSL_KEY_PATH: ${SSL_KEY_PATH}
        SSL_COUNTRY: ${SSL_COUNTRY}
        SSL_STATE: ${SSL_STATE}
        SSL_LOCALITY: ${SSL_LOCALITY}
        SSL_ORGANIZATION: ${SSL_ORGANIZATION}
        SSL_UNIT: ${SSL_UNIT}
        SSL_COMMON_NAME: ${SSL_COMMON_NAME}
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/inception/
    networks:
      - inception
    init: true
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress

# Volumes ---------------------------------------------------------------------
volumes:
  database:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/database
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/wordpress_files

# Networks --------------------------------------------------------------------
networks:
  inception:
    driver: bridge
